// ── Permission Code Registry ───────────────────────────────────────────────
// Pattern: {module}:{resource}:{action}
// This is the single source of truth for all permission codes.
// Used in: seed.ts, tRPC routers (modulePermissionProcedure), sidebar route config, PermissionGuard.

// ── System / Administration ────────────────────────────────────────────────
export const P = {
  // System
  SYSTEM_USER_READ:          "system:user:read",
  SYSTEM_USER_CREATE:        "system:user:create",
  SYSTEM_USER_UPDATE:        "system:user:update",
  SYSTEM_USER_DELETE:        "system:user:delete",
  SYSTEM_ROLE_READ:          "system:role:read",
  SYSTEM_ROLE_CREATE:        "system:role:create",
  SYSTEM_ROLE_UPDATE:        "system:role:update",
  SYSTEM_ROLE_DELETE:        "system:role:delete",
  SYSTEM_PERMISSION_READ:    "system:permission:read",
  SYSTEM_SETTINGS_READ:      "system:settings:read",
  SYSTEM_SETTINGS_MANAGE:    "system:settings:manage",
  SYSTEM_MODULE_MANAGE:      "system:module:manage",
  SYSTEM_LICENSE_READ:       "system:license:read",

  // ── Finance ──────────────────────────────────────────────────────────────
  FINANCE_ACCOUNT_READ:           "finance:account:read",
  FINANCE_ACCOUNT_CREATE:         "finance:account:create",
  FINANCE_ACCOUNT_UPDATE:         "finance:account:update",
  FINANCE_ACCOUNT_DELETE:         "finance:account:delete",
  FINANCE_JOURNAL_READ:           "finance:journal:read",
  FINANCE_JOURNAL_CREATE:         "finance:journal:create",
  FINANCE_JOURNAL_UPDATE:         "finance:journal:update",
  FINANCE_JOURNAL_DELETE:         "finance:journal:delete",
  FINANCE_TAX_READ:               "finance:tax:read",
  FINANCE_TAX_CREATE:             "finance:tax:create",
  FINANCE_TAX_UPDATE:             "finance:tax:update",
  FINANCE_TAX_DELETE:             "finance:tax:delete",
  FINANCE_PAYMENT_TERM_READ:      "finance:paymentTerm:read",
  FINANCE_PAYMENT_TERM_CREATE:    "finance:paymentTerm:create",
  FINANCE_PAYMENT_TERM_UPDATE:    "finance:paymentTerm:update",
  FINANCE_PAYMENT_TERM_DELETE:    "finance:paymentTerm:delete",
  FINANCE_PARTNER_READ:           "finance:partner:read",
  FINANCE_PARTNER_CREATE:         "finance:partner:create",
  FINANCE_PARTNER_UPDATE:         "finance:partner:update",
  FINANCE_PARTNER_DELETE:         "finance:partner:delete",
  FINANCE_MOVE_READ:              "finance:move:read",
  FINANCE_MOVE_CREATE:            "finance:move:create",
  FINANCE_MOVE_UPDATE:            "finance:move:update",
  FINANCE_MOVE_DELETE:            "finance:move:delete",
  FINANCE_MOVE_CONFIRM:           "finance:move:confirm",
  FINANCE_MOVE_CANCEL:            "finance:move:cancel",
  FINANCE_INVOICE_READ:           "finance:invoice:read",
  FINANCE_INVOICE_CREATE:         "finance:invoice:create",
  FINANCE_INVOICE_UPDATE:         "finance:invoice:update",
  FINANCE_INVOICE_CANCEL:         "finance:invoice:cancel",
  FINANCE_INVOICE_EXPORT:         "finance:invoice:export",
  FINANCE_BILL_READ:              "finance:bill:read",
  FINANCE_BILL_CREATE:            "finance:bill:create",
  FINANCE_BILL_UPDATE:            "finance:bill:update",
  FINANCE_BILL_CANCEL:            "finance:bill:cancel",
  FINANCE_BILL_EXPORT:            "finance:bill:export",
  FINANCE_PAYMENT_READ:           "finance:payment:read",
  FINANCE_PAYMENT_CREATE:         "finance:payment:create",
  FINANCE_PAYMENT_CONFIRM:        "finance:payment:confirm",
  FINANCE_PAYMENT_CANCEL:         "finance:payment:cancel",
  FINANCE_BANK_STATEMENT_READ:    "finance:bankStatement:read",
  FINANCE_BANK_STATEMENT_CREATE:  "finance:bankStatement:create",
  FINANCE_BANK_STATEMENT_IMPORT:  "finance:bankStatement:import",
  FINANCE_BANK_STATEMENT_VALIDATE:"finance:bankStatement:validate",
  FINANCE_BANK_STATEMENT_DELETE:  "finance:bankStatement:delete",
  FINANCE_RECONCILIATION_READ:    "finance:reconciliation:read",
  FINANCE_RECONCILIATION_DO:      "finance:reconciliation:reconcile",
  FINANCE_BATCH_PAYMENT_READ:     "finance:batchPayment:read",
  FINANCE_BATCH_PAYMENT_CREATE:   "finance:batchPayment:create",
  FINANCE_BATCH_PAYMENT_CONFIRM:  "finance:batchPayment:confirm",
  FINANCE_BATCH_PAYMENT_DELETE:   "finance:batchPayment:delete",
  FINANCE_BUDGET_READ:            "finance:budget:read",
  FINANCE_BUDGET_CREATE:          "finance:budget:create",
  FINANCE_BUDGET_UPDATE:          "finance:budget:update",
  FINANCE_BUDGET_DELETE:          "finance:budget:delete",
  FINANCE_ASSET_READ:             "finance:asset:read",
  FINANCE_ASSET_CREATE:           "finance:asset:create",
  FINANCE_ASSET_UPDATE:           "finance:asset:update",
  FINANCE_ASSET_DELETE:           "finance:asset:delete",
  FINANCE_DEFERRED_READ:          "finance:deferred:read",
  FINANCE_DEFERRED_CREATE:        "finance:deferred:create",
  FINANCE_DEFERRED_UPDATE:        "finance:deferred:update",
  FINANCE_PERIOD_READ:            "finance:period:read",
  FINANCE_PERIOD_MANAGE:          "finance:period:manage",
  FINANCE_LOCK_DATE_MANAGE:       "finance:lockDate:manage",
  FINANCE_FISCAL_POSITION_READ:   "finance:fiscalPosition:read",
  FINANCE_FISCAL_POSITION_CREATE: "finance:fiscalPosition:create",
  FINANCE_FISCAL_POSITION_UPDATE: "finance:fiscalPosition:update",
  FINANCE_FISCAL_POSITION_DELETE: "finance:fiscalPosition:delete",
  FINANCE_CURRENCY_READ:          "finance:currency:read",
  FINANCE_CURRENCY_MANAGE:        "finance:currency:manage",
  FINANCE_REPORT_READ:            "finance:report:read",
  FINANCE_AUDIT_READ:             "finance:auditTrail:read",
  FINANCE_SETTINGS_MANAGE:        "finance:settings:manage",

  // ── Contracting ───────────────────────────────────────────────────────────
  CONTRACTING_HOTEL_READ:        "contracting:hotel:read",
  CONTRACTING_HOTEL_CREATE:      "contracting:hotel:create",
  CONTRACTING_HOTEL_UPDATE:      "contracting:hotel:update",
  CONTRACTING_HOTEL_DELETE:      "contracting:hotel:delete",
  CONTRACTING_DESTINATION_READ:  "contracting:destination:read",
  CONTRACTING_DESTINATION_CREATE:"contracting:destination:create",
  CONTRACTING_DESTINATION_UPDATE:"contracting:destination:update",
  CONTRACTING_DESTINATION_DELETE:"contracting:destination:delete",
  CONTRACTING_MARKET_READ:       "contracting:market:read",
  CONTRACTING_MARKET_CREATE:     "contracting:market:create",
  CONTRACTING_MARKET_UPDATE:     "contracting:market:update",
  CONTRACTING_MARKET_DELETE:     "contracting:market:delete",
  CONTRACTING_ROOM_TYPE_READ:    "contracting:roomType:read",
  CONTRACTING_ROOM_TYPE_CREATE:  "contracting:roomType:create",
  CONTRACTING_ROOM_TYPE_UPDATE:  "contracting:roomType:update",
  CONTRACTING_ROOM_TYPE_DELETE:  "contracting:roomType:delete",
  CONTRACTING_MEAL_BASIS_READ:   "contracting:mealBasis:read",
  CONTRACTING_MEAL_BASIS_CREATE: "contracting:mealBasis:create",
  CONTRACTING_MEAL_BASIS_UPDATE: "contracting:mealBasis:update",
  CONTRACTING_MEAL_BASIS_DELETE: "contracting:mealBasis:delete",
  CONTRACTING_CONTRACT_READ:     "contracting:contract:read",
  CONTRACTING_CONTRACT_CREATE:   "contracting:contract:create",
  CONTRACTING_CONTRACT_UPDATE:   "contracting:contract:update",
  CONTRACTING_CONTRACT_DELETE:   "contracting:contract:delete",
  CONTRACTING_CONTRACT_POST:     "contracting:contract:post",
  CONTRACTING_CONTRACT_PUBLISH:  "contracting:contract:publish",
  CONTRACTING_RATE_READ:         "contracting:rate:read",
  CONTRACTING_RATE_CREATE:       "contracting:rate:create",
  CONTRACTING_RATE_UPDATE:       "contracting:rate:update",
  CONTRACTING_RATE_DELETE:       "contracting:rate:delete",
  CONTRACTING_SEASON_READ:       "contracting:season:read",
  CONTRACTING_SEASON_CREATE:     "contracting:season:create",
  CONTRACTING_SEASON_UPDATE:     "contracting:season:update",
  CONTRACTING_SEASON_DELETE:     "contracting:season:delete",
  CONTRACTING_SUPPLEMENT_READ:   "contracting:supplement:read",
  CONTRACTING_SUPPLEMENT_CREATE: "contracting:supplement:create",
  CONTRACTING_SUPPLEMENT_UPDATE: "contracting:supplement:update",
  CONTRACTING_SUPPLEMENT_DELETE: "contracting:supplement:delete",
  CONTRACTING_OFFER_READ:        "contracting:offer:read",
  CONTRACTING_OFFER_CREATE:      "contracting:offer:create",
  CONTRACTING_OFFER_UPDATE:      "contracting:offer:update",
  CONTRACTING_OFFER_DELETE:      "contracting:offer:delete",
  CONTRACTING_POLICY_READ:       "contracting:policy:read",
  CONTRACTING_POLICY_CREATE:     "contracting:policy:create",
  CONTRACTING_POLICY_UPDATE:     "contracting:policy:update",
  CONTRACTING_POLICY_DELETE:     "contracting:policy:delete",
  CONTRACTING_MARKUP_READ:       "contracting:markup:read",
  CONTRACTING_MARKUP_CREATE:     "contracting:markup:create",
  CONTRACTING_MARKUP_UPDATE:     "contracting:markup:update",
  CONTRACTING_MARKUP_DELETE:     "contracting:markup:delete",
  CONTRACTING_ALLOTMENT_READ:    "contracting:allotment:read",
  CONTRACTING_ALLOTMENT_CREATE:  "contracting:allotment:create",
  CONTRACTING_ALLOTMENT_UPDATE:  "contracting:allotment:update",
  CONTRACTING_TARIFF_READ:       "contracting:tariff:read",
  CONTRACTING_TARIFF_EXPORT:     "contracting:tariff:export",
  CONTRACTING_REPORT_READ:       "contracting:report:read",

  // ── Reservations ─────────────────────────────────────────────────────────
  RESERVATIONS_BOOKING_READ:     "reservations:booking:read",
  RESERVATIONS_BOOKING_CREATE:   "reservations:booking:create",
  RESERVATIONS_BOOKING_UPDATE:   "reservations:booking:update",
  RESERVATIONS_BOOKING_DELETE:   "reservations:booking:delete",
  RESERVATIONS_BOOKING_CONFIRM:  "reservations:booking:confirm",
  RESERVATIONS_BOOKING_CANCEL:   "reservations:booking:cancel",
  RESERVATIONS_BOOKING_EXPORT:   "reservations:booking:export",
  RESERVATIONS_PAYMENT_READ:     "reservations:payment:read",
  RESERVATIONS_PAYMENT_CREATE:   "reservations:payment:create",
  RESERVATIONS_PAYMENT_CONFIRM:  "reservations:payment:confirm",
  RESERVATIONS_PAYMENT_CANCEL:   "reservations:payment:cancel",
  RESERVATIONS_GUEST_READ:       "reservations:guest:read",
  RESERVATIONS_GUEST_CREATE:     "reservations:guest:create",
  RESERVATIONS_GUEST_UPDATE:     "reservations:guest:update",
  RESERVATIONS_GUEST_DELETE:     "reservations:guest:delete",
  RESERVATIONS_VOUCHER_READ:     "reservations:voucher:read",
  RESERVATIONS_VOUCHER_CREATE:   "reservations:voucher:create",
  RESERVATIONS_VOUCHER_EXPORT:   "reservations:voucher:export",
  RESERVATIONS_COMMUNICATION_READ:   "reservations:communication:read",
  RESERVATIONS_COMMUNICATION_CREATE: "reservations:communication:create",
  RESERVATIONS_HOTEL_CREDIT_READ:    "reservations:hotelCredit:read",
  RESERVATIONS_HOTEL_CREDIT_CREATE:  "reservations:hotelCredit:create",
  RESERVATIONS_HOTEL_CREDIT_UPDATE:  "reservations:hotelCredit:update",
  RESERVATIONS_REPORT_READ:      "reservations:report:read",

  // ── Traffic ───────────────────────────────────────────────────────────────
  TRAFFIC_JOB_READ:              "traffic:job:read",
  TRAFFIC_JOB_CREATE:            "traffic:job:create",
  TRAFFIC_JOB_UPDATE:            "traffic:job:update",
  TRAFFIC_JOB_DELETE:            "traffic:job:delete",
  TRAFFIC_VEHICLE_READ:          "traffic:vehicle:read",
  TRAFFIC_VEHICLE_CREATE:        "traffic:vehicle:create",
  TRAFFIC_VEHICLE_UPDATE:        "traffic:vehicle:update",
  TRAFFIC_VEHICLE_DELETE:        "traffic:vehicle:delete",
  TRAFFIC_DRIVER_READ:           "traffic:driver:read",
  TRAFFIC_DRIVER_CREATE:         "traffic:driver:create",
  TRAFFIC_DRIVER_UPDATE:         "traffic:driver:update",
  TRAFFIC_DRIVER_DELETE:         "traffic:driver:delete",
  TRAFFIC_ZONE_READ:             "traffic:zone:read",
  TRAFFIC_ZONE_CREATE:           "traffic:zone:create",
  TRAFFIC_ZONE_UPDATE:           "traffic:zone:update",
  TRAFFIC_ZONE_DELETE:           "traffic:zone:delete",
  TRAFFIC_AIRPORT_READ:          "traffic:airport:read",
  TRAFFIC_AIRPORT_CREATE:        "traffic:airport:create",
  TRAFFIC_AIRPORT_UPDATE:        "traffic:airport:update",
  TRAFFIC_PRICING_READ:          "traffic:pricing:read",
  TRAFFIC_PRICING_CREATE:        "traffic:pricing:create",
  TRAFFIC_PRICING_UPDATE:        "traffic:pricing:update",
  TRAFFIC_PRICING_DELETE:        "traffic:pricing:delete",
  TRAFFIC_DISPATCH_READ:         "traffic:dispatch:read",
  TRAFFIC_DISPATCH_MANAGE:       "traffic:dispatch:manage",
  TRAFFIC_ASSIGNMENT_READ:       "traffic:assignment:read",
  TRAFFIC_ASSIGNMENT_MANAGE:     "traffic:assignment:manage",
  TRAFFIC_GUEST_BOOKING_READ:    "traffic:guestBooking:read",
  TRAFFIC_GUEST_BOOKING_CREATE:  "traffic:guestBooking:create",
  TRAFFIC_GUEST_BOOKING_UPDATE:  "traffic:guestBooking:update",
  TRAFFIC_REPORT_READ:           "traffic:report:read",
  TRAFFIC_SETTINGS_MANAGE:       "traffic:settings:manage",

  // ── CRM / Excursion Sales ─────────────────────────────────────────────────
  CRM_LEAD_READ:                 "crm:lead:read",
  CRM_LEAD_CREATE:               "crm:lead:create",
  CRM_LEAD_UPDATE:               "crm:lead:update",
  CRM_LEAD_DELETE:               "crm:lead:delete",
  CRM_OPPORTUNITY_READ:          "crm:opportunity:read",
  CRM_OPPORTUNITY_CREATE:        "crm:opportunity:create",
  CRM_OPPORTUNITY_UPDATE:        "crm:opportunity:update",
  CRM_OPPORTUNITY_DELETE:        "crm:opportunity:delete",
  CRM_CUSTOMER_READ:             "crm:customer:read",
  CRM_CUSTOMER_CREATE:           "crm:customer:create",
  CRM_CUSTOMER_UPDATE:           "crm:customer:update",
  CRM_CUSTOMER_DELETE:           "crm:customer:delete",
  CRM_EXCURSION_READ:            "crm:excursion:read",
  CRM_EXCURSION_CREATE:          "crm:excursion:create",
  CRM_EXCURSION_UPDATE:          "crm:excursion:update",
  CRM_EXCURSION_DELETE:          "crm:excursion:delete",
  CRM_EXCURSION_EXPORT:          "crm:excursion:export",
  CRM_BOOKING_READ:              "crm:booking:read",
  CRM_BOOKING_CREATE:            "crm:booking:create",
  CRM_BOOKING_UPDATE:            "crm:booking:update",
  CRM_BOOKING_DELETE:            "crm:booking:delete",
  CRM_BOOKING_CONFIRM:           "crm:booking:confirm",
  CRM_BOOKING_CANCEL:            "crm:booking:cancel",
  CRM_BOOKING_EXPORT:            "crm:booking:export",
  CRM_SUPPLIER_READ:             "crm:supplier:read",
  CRM_SUPPLIER_CREATE:           "crm:supplier:create",
  CRM_SUPPLIER_UPDATE:           "crm:supplier:update",
  CRM_ACTIVITY_READ:             "crm:activity:read",
  CRM_ACTIVITY_CREATE:           "crm:activity:create",
  CRM_ACTIVITY_UPDATE:           "crm:activity:update",
  CRM_ACTIVITY_DELETE:           "crm:activity:delete",
  CRM_COST_SHEET_READ:           "crm:costSheet:read",
  CRM_COST_SHEET_CREATE:         "crm:costSheet:create",
  CRM_COST_SHEET_UPDATE:         "crm:costSheet:update",
  CRM_COST_SHEET_DELETE:         "crm:costSheet:delete",
  CRM_REPORT_READ:               "crm:report:read",

  // ── Tour Operations ───────────────────────────────────────────────────────
  TOUR_OPS_FILE_READ:            "tour-ops:file:read",
  TOUR_OPS_FILE_CREATE:          "tour-ops:file:create",
  TOUR_OPS_FILE_UPDATE:          "tour-ops:file:update",
  TOUR_OPS_FILE_DELETE:          "tour-ops:file:delete",
  TOUR_OPS_PACKAGE_READ:         "tour-ops:package:read",
  TOUR_OPS_PACKAGE_CREATE:       "tour-ops:package:create",
  TOUR_OPS_PACKAGE_UPDATE:       "tour-ops:package:update",
  TOUR_OPS_PACKAGE_DELETE:       "tour-ops:package:delete",
  TOUR_OPS_QUOTATION_READ:       "tour-ops:quotation:read",
  TOUR_OPS_QUOTATION_CREATE:     "tour-ops:quotation:create",
  TOUR_OPS_QUOTATION_UPDATE:     "tour-ops:quotation:update",
  TOUR_OPS_QUOTATION_DELETE:     "tour-ops:quotation:delete",
  TOUR_OPS_QUOTATION_EXPORT:     "tour-ops:quotation:export",
  TOUR_OPS_TICKET_READ:          "tour-ops:flightTicket:read",
  TOUR_OPS_TICKET_CREATE:        "tour-ops:flightTicket:create",
  TOUR_OPS_TICKET_UPDATE:        "tour-ops:flightTicket:update",
  TOUR_OPS_TICKET_DELETE:        "tour-ops:flightTicket:delete",
  TOUR_OPS_TICKET_POST:          "tour-ops:flightTicket:post",
  TOUR_OPS_TICKET_CANCEL:        "tour-ops:flightTicket:cancel",
  TOUR_OPS_COMPONENT_READ:       "tour-ops:component:read",
  TOUR_OPS_COMPONENT_CREATE:     "tour-ops:component:create",
  TOUR_OPS_COMPONENT_UPDATE:     "tour-ops:component:update",
  TOUR_OPS_COMPONENT_DELETE:     "tour-ops:component:delete",
  TOUR_OPS_DISPATCH_READ:        "tour-ops:dispatch:read",
  TOUR_OPS_DISPATCH_MANAGE:      "tour-ops:dispatch:manage",
  TOUR_OPS_PNL_READ:             "tour-ops:pnl:read",
  TOUR_OPS_REPORT_READ:          "tour-ops:report:read",

  // ── B2C Website ───────────────────────────────────────────────────────────
  B2C_BRANDING_READ:             "b2c-site:branding:read",
  B2C_BRANDING_MANAGE:           "b2c-site:branding:manage",
  B2C_HERO_READ:                 "b2c-site:heroSlide:read",
  B2C_HERO_CREATE:               "b2c-site:heroSlide:create",
  B2C_HERO_UPDATE:               "b2c-site:heroSlide:update",
  B2C_HERO_DELETE:               "b2c-site:heroSlide:delete",
  B2C_PAGE_READ:                 "b2c-site:page:read",
  B2C_PAGE_CREATE:               "b2c-site:page:create",
  B2C_PAGE_UPDATE:               "b2c-site:page:update",
  B2C_PAGE_DELETE:               "b2c-site:page:delete",
  B2C_BLOG_READ:                 "b2c-site:blog:read",
  B2C_BLOG_CREATE:               "b2c-site:blog:create",
  B2C_BLOG_UPDATE:               "b2c-site:blog:update",
  B2C_BLOG_DELETE:               "b2c-site:blog:delete",
  B2C_FAQ_READ:                  "b2c-site:faq:read",
  B2C_FAQ_CREATE:                "b2c-site:faq:create",
  B2C_FAQ_UPDATE:                "b2c-site:faq:update",
  B2C_FAQ_DELETE:                "b2c-site:faq:delete",
  B2C_TESTIMONIAL_READ:          "b2c-site:testimonial:read",
  B2C_TESTIMONIAL_CREATE:        "b2c-site:testimonial:create",
  B2C_TESTIMONIAL_UPDATE:        "b2c-site:testimonial:update",
  B2C_TESTIMONIAL_DELETE:        "b2c-site:testimonial:delete",
  B2C_INQUIRY_READ:              "b2c-site:inquiry:read",
  B2C_INQUIRY_DELETE:            "b2c-site:inquiry:delete",
  B2C_NEWSLETTER_READ:           "b2c-site:newsletter:read",
  B2C_NEWSLETTER_MANAGE:         "b2c-site:newsletter:manage",
  B2C_MARKUP_READ:               "b2c-site:markup:read",
  B2C_MARKUP_CREATE:             "b2c-site:markup:create",
  B2C_MARKUP_UPDATE:             "b2c-site:markup:update",
  B2C_MARKUP_DELETE:             "b2c-site:markup:delete",

  // ── B2B Portal ────────────────────────────────────────────────────────────
  B2B_TOUR_OPERATOR_READ:        "b2b-portal:tourOperator:read",
  B2B_TOUR_OPERATOR_CREATE:      "b2b-portal:tourOperator:create",
  B2B_TOUR_OPERATOR_UPDATE:      "b2b-portal:tourOperator:update",
  B2B_TOUR_OPERATOR_DELETE:      "b2b-portal:tourOperator:delete",
  B2B_TRAVEL_AGENT_READ:         "b2b-portal:travelAgent:read",
  B2B_TRAVEL_AGENT_CREATE:       "b2b-portal:travelAgent:create",
  B2B_TRAVEL_AGENT_UPDATE:       "b2b-portal:travelAgent:update",
  B2B_TRAVEL_AGENT_DELETE:       "b2b-portal:travelAgent:delete",
  B2B_PARTNER_USER_READ:         "b2b-portal:partnerUser:read",
  B2B_PARTNER_USER_CREATE:       "b2b-portal:partnerUser:create",
  B2B_PARTNER_USER_UPDATE:       "b2b-portal:partnerUser:update",
  B2B_RESERVATION_READ:          "b2b-portal:reservation:read",
  B2B_RESERVATION_CREATE:        "b2b-portal:reservation:create",
  B2B_RESERVATION_UPDATE:        "b2b-portal:reservation:update",
  B2B_VOUCHER_READ:              "b2b-portal:voucher:read",
  B2B_VOUCHER_CREATE:            "b2b-portal:voucher:create",
  B2B_CREDIT_READ:               "b2b-portal:credit:read",
  B2B_CREDIT_MANAGE:             "b2b-portal:credit:manage",
  B2B_MARKUP_READ:               "b2b-portal:markup:read",
  B2B_MARKUP_CREATE:             "b2b-portal:markup:create",
  B2B_MARKUP_UPDATE:             "b2b-portal:markup:update",
  B2B_MARKUP_DELETE:             "b2b-portal:markup:delete",
  B2B_RATE_SHEET_READ:           "b2b-portal:rateSheet:read",
  B2B_RATE_SHEET_CREATE:         "b2b-portal:rateSheet:create",
  B2B_RATE_SHEET_UPDATE:         "b2b-portal:rateSheet:update",
  B2B_RATE_SHEET_DELETE:         "b2b-portal:rateSheet:delete",
  B2B_REPORT_READ:               "b2b-portal:report:read",

  // ── Nile Cruises ──────────────────────────────────────────────────────────
  NC_DASHBOARD_READ:             "nile-cruises:dashboard:read",
  NC_BOAT_READ:                  "nile-cruises:boat:read",
  NC_BOAT_CREATE:                "nile-cruises:boat:create",
  NC_BOAT_UPDATE:                "nile-cruises:boat:update",
  NC_BOAT_DELETE:                "nile-cruises:boat:delete",
  NC_CONTRACT_READ:              "nile-cruises:contract:read",
  NC_CONTRACT_CREATE:            "nile-cruises:contract:create",
  NC_CONTRACT_UPDATE:            "nile-cruises:contract:update",
  NC_CONTRACT_DELETE:            "nile-cruises:contract:delete",
  NC_CONTRACT_PUBLISH:           "nile-cruises:contract:publish",
  NC_DEPARTURE_READ:             "nile-cruises:departure:read",
  NC_DEPARTURE_CREATE:           "nile-cruises:departure:create",
  NC_DEPARTURE_UPDATE:           "nile-cruises:departure:update",
  NC_DEPARTURE_DELETE:           "nile-cruises:departure:delete",
  NC_BOOKING_READ:               "nile-cruises:booking:read",
  NC_BOOKING_CREATE:             "nile-cruises:booking:create",
  NC_BOOKING_UPDATE:             "nile-cruises:booking:update",
  NC_BOOKING_DELETE:             "nile-cruises:booking:delete",
  NC_BOOKING_CONFIRM:            "nile-cruises:booking:confirm",
  NC_BOOKING_CANCEL:             "nile-cruises:booking:cancel",
  NC_MANIFEST_READ:              "nile-cruises:manifest:read",
  NC_MANIFEST_GENERATE:          "nile-cruises:manifest:generate",
  NC_MANIFEST_SUBMIT:            "nile-cruises:manifest:submit",
  NC_REPORTS_READ:               "nile-cruises:reports:read",
  NC_SEARCH_READ:                "nile-cruises:search:read",
  NC_SETTINGS_READ:              "nile-cruises:settings:read",
  NC_SETTINGS_UPDATE:            "nile-cruises:settings:update",
} as const;

export type PermissionCode = typeof P[keyof typeof P];

// All permission codes as a flat array (used for seeding)
export const ALL_PERMISSIONS: { code: PermissionCode; module: string; resource: string; action: string; displayName: string }[] = [
  // System
  { code: P.SYSTEM_USER_READ,          module: "system",       resource: "user",           action: "read",      displayName: "View Users" },
  { code: P.SYSTEM_USER_CREATE,        module: "system",       resource: "user",           action: "create",    displayName: "Create Users" },
  { code: P.SYSTEM_USER_UPDATE,        module: "system",       resource: "user",           action: "update",    displayName: "Edit Users" },
  { code: P.SYSTEM_USER_DELETE,        module: "system",       resource: "user",           action: "delete",    displayName: "Delete Users" },
  { code: P.SYSTEM_ROLE_READ,          module: "system",       resource: "role",           action: "read",      displayName: "View Roles" },
  { code: P.SYSTEM_ROLE_CREATE,        module: "system",       resource: "role",           action: "create",    displayName: "Create Roles" },
  { code: P.SYSTEM_ROLE_UPDATE,        module: "system",       resource: "role",           action: "update",    displayName: "Edit Roles" },
  { code: P.SYSTEM_ROLE_DELETE,        module: "system",       resource: "role",           action: "delete",    displayName: "Delete Roles" },
  { code: P.SYSTEM_PERMISSION_READ,    module: "system",       resource: "permission",     action: "read",      displayName: "View Permissions" },
  { code: P.SYSTEM_SETTINGS_READ,      module: "system",       resource: "settings",       action: "read",      displayName: "View Settings" },
  { code: P.SYSTEM_SETTINGS_MANAGE,    module: "system",       resource: "settings",       action: "manage",    displayName: "Manage Settings" },
  { code: P.SYSTEM_MODULE_MANAGE,      module: "system",       resource: "module",         action: "manage",    displayName: "Manage Modules" },
  { code: P.SYSTEM_LICENSE_READ,       module: "system",       resource: "license",        action: "read",      displayName: "View License" },
  // Finance
  { code: P.FINANCE_ACCOUNT_READ,      module: "finance",      resource: "account",        action: "read",      displayName: "View Chart of Accounts" },
  { code: P.FINANCE_ACCOUNT_CREATE,    module: "finance",      resource: "account",        action: "create",    displayName: "Create Accounts" },
  { code: P.FINANCE_ACCOUNT_UPDATE,    module: "finance",      resource: "account",        action: "update",    displayName: "Edit Accounts" },
  { code: P.FINANCE_ACCOUNT_DELETE,    module: "finance",      resource: "account",        action: "delete",    displayName: "Delete Accounts" },
  { code: P.FINANCE_JOURNAL_READ,      module: "finance",      resource: "journal",        action: "read",      displayName: "View Journals" },
  { code: P.FINANCE_JOURNAL_CREATE,    module: "finance",      resource: "journal",        action: "create",    displayName: "Create Journals" },
  { code: P.FINANCE_JOURNAL_UPDATE,    module: "finance",      resource: "journal",        action: "update",    displayName: "Edit Journals" },
  { code: P.FINANCE_JOURNAL_DELETE,    module: "finance",      resource: "journal",        action: "delete",    displayName: "Delete Journals" },
  { code: P.FINANCE_TAX_READ,          module: "finance",      resource: "tax",            action: "read",      displayName: "View Taxes" },
  { code: P.FINANCE_TAX_CREATE,        module: "finance",      resource: "tax",            action: "create",    displayName: "Create Taxes" },
  { code: P.FINANCE_TAX_UPDATE,        module: "finance",      resource: "tax",            action: "update",    displayName: "Edit Taxes" },
  { code: P.FINANCE_TAX_DELETE,        module: "finance",      resource: "tax",            action: "delete",    displayName: "Delete Taxes" },
  { code: P.FINANCE_PAYMENT_TERM_READ,    module: "finance",   resource: "paymentTerm",    action: "read",      displayName: "View Payment Terms" },
  { code: P.FINANCE_PAYMENT_TERM_CREATE,  module: "finance",   resource: "paymentTerm",    action: "create",    displayName: "Create Payment Terms" },
  { code: P.FINANCE_PAYMENT_TERM_UPDATE,  module: "finance",   resource: "paymentTerm",    action: "update",    displayName: "Edit Payment Terms" },
  { code: P.FINANCE_PAYMENT_TERM_DELETE,  module: "finance",   resource: "paymentTerm",    action: "delete",    displayName: "Delete Payment Terms" },
  { code: P.FINANCE_PARTNER_READ,         module: "finance",   resource: "partner",        action: "read",      displayName: "View Partners" },
  { code: P.FINANCE_PARTNER_CREATE,       module: "finance",   resource: "partner",        action: "create",    displayName: "Create Partners" },
  { code: P.FINANCE_PARTNER_UPDATE,       module: "finance",   resource: "partner",        action: "update",    displayName: "Edit Partners" },
  { code: P.FINANCE_PARTNER_DELETE,       module: "finance",   resource: "partner",        action: "delete",    displayName: "Delete Partners" },
  { code: P.FINANCE_MOVE_READ,            module: "finance",   resource: "move",           action: "read",      displayName: "View Journal Entries" },
  { code: P.FINANCE_MOVE_CREATE,          module: "finance",   resource: "move",           action: "create",    displayName: "Create Journal Entries" },
  { code: P.FINANCE_MOVE_UPDATE,          module: "finance",   resource: "move",           action: "update",    displayName: "Edit Journal Entries" },
  { code: P.FINANCE_MOVE_DELETE,          module: "finance",   resource: "move",           action: "delete",    displayName: "Delete Journal Entries" },
  { code: P.FINANCE_MOVE_CONFIRM,         module: "finance",   resource: "move",           action: "confirm",   displayName: "Confirm Journal Entries" },
  { code: P.FINANCE_MOVE_CANCEL,          module: "finance",   resource: "move",           action: "cancel",    displayName: "Cancel Journal Entries" },
  { code: P.FINANCE_INVOICE_READ,         module: "finance",   resource: "invoice",        action: "read",      displayName: "View Invoices" },
  { code: P.FINANCE_INVOICE_CREATE,       module: "finance",   resource: "invoice",        action: "create",    displayName: "Create Invoices" },
  { code: P.FINANCE_INVOICE_UPDATE,       module: "finance",   resource: "invoice",        action: "update",    displayName: "Edit Invoices" },
  { code: P.FINANCE_INVOICE_CANCEL,       module: "finance",   resource: "invoice",        action: "cancel",    displayName: "Cancel Invoices" },
  { code: P.FINANCE_INVOICE_EXPORT,       module: "finance",   resource: "invoice",        action: "export",    displayName: "Export Invoices" },
  { code: P.FINANCE_BILL_READ,            module: "finance",   resource: "bill",           action: "read",      displayName: "View Bills" },
  { code: P.FINANCE_BILL_CREATE,          module: "finance",   resource: "bill",           action: "create",    displayName: "Create Bills" },
  { code: P.FINANCE_BILL_UPDATE,          module: "finance",   resource: "bill",           action: "update",    displayName: "Edit Bills" },
  { code: P.FINANCE_BILL_CANCEL,          module: "finance",   resource: "bill",           action: "cancel",    displayName: "Cancel Bills" },
  { code: P.FINANCE_BILL_EXPORT,          module: "finance",   resource: "bill",           action: "export",    displayName: "Export Bills" },
  { code: P.FINANCE_PAYMENT_READ,         module: "finance",   resource: "payment",        action: "read",      displayName: "View Payments" },
  { code: P.FINANCE_PAYMENT_CREATE,       module: "finance",   resource: "payment",        action: "create",    displayName: "Create Payments" },
  { code: P.FINANCE_PAYMENT_CONFIRM,      module: "finance",   resource: "payment",        action: "confirm",   displayName: "Confirm Payments" },
  { code: P.FINANCE_PAYMENT_CANCEL,       module: "finance",   resource: "payment",        action: "cancel",    displayName: "Cancel Payments" },
  { code: P.FINANCE_BANK_STATEMENT_READ,  module: "finance",   resource: "bankStatement",  action: "read",      displayName: "View Bank Statements" },
  { code: P.FINANCE_BANK_STATEMENT_CREATE,module: "finance",   resource: "bankStatement",  action: "create",    displayName: "Create Bank Statements" },
  { code: P.FINANCE_BANK_STATEMENT_IMPORT,module: "finance",   resource: "bankStatement",  action: "import",    displayName: "Import Bank Statements" },
  { code: P.FINANCE_BANK_STATEMENT_VALIDATE,module:"finance",  resource: "bankStatement",  action: "validate",  displayName: "Validate Bank Statements" },
  { code: P.FINANCE_BANK_STATEMENT_DELETE,module: "finance",   resource: "bankStatement",  action: "delete",    displayName: "Delete Bank Statements" },
  { code: P.FINANCE_RECONCILIATION_READ,  module: "finance",   resource: "reconciliation", action: "read",      displayName: "View Reconciliation" },
  { code: P.FINANCE_RECONCILIATION_DO,    module: "finance",   resource: "reconciliation", action: "reconcile", displayName: "Reconcile Accounts" },
  { code: P.FINANCE_BATCH_PAYMENT_READ,   module: "finance",   resource: "batchPayment",   action: "read",      displayName: "View Batch Payments" },
  { code: P.FINANCE_BATCH_PAYMENT_CREATE, module: "finance",   resource: "batchPayment",   action: "create",    displayName: "Create Batch Payments" },
  { code: P.FINANCE_BATCH_PAYMENT_CONFIRM,module: "finance",   resource: "batchPayment",   action: "confirm",   displayName: "Confirm Batch Payments" },
  { code: P.FINANCE_BATCH_PAYMENT_DELETE, module: "finance",   resource: "batchPayment",   action: "delete",    displayName: "Delete Batch Payments" },
  { code: P.FINANCE_BUDGET_READ,          module: "finance",   resource: "budget",         action: "read",      displayName: "View Budgets" },
  { code: P.FINANCE_BUDGET_CREATE,        module: "finance",   resource: "budget",         action: "create",    displayName: "Create Budgets" },
  { code: P.FINANCE_BUDGET_UPDATE,        module: "finance",   resource: "budget",         action: "update",    displayName: "Edit Budgets" },
  { code: P.FINANCE_BUDGET_DELETE,        module: "finance",   resource: "budget",         action: "delete",    displayName: "Delete Budgets" },
  { code: P.FINANCE_ASSET_READ,           module: "finance",   resource: "asset",          action: "read",      displayName: "View Assets" },
  { code: P.FINANCE_ASSET_CREATE,         module: "finance",   resource: "asset",          action: "create",    displayName: "Create Assets" },
  { code: P.FINANCE_ASSET_UPDATE,         module: "finance",   resource: "asset",          action: "update",    displayName: "Edit Assets" },
  { code: P.FINANCE_ASSET_DELETE,         module: "finance",   resource: "asset",          action: "delete",    displayName: "Delete Assets" },
  { code: P.FINANCE_DEFERRED_READ,        module: "finance",   resource: "deferred",       action: "read",      displayName: "View Deferred Revenue/Expense" },
  { code: P.FINANCE_DEFERRED_CREATE,      module: "finance",   resource: "deferred",       action: "create",    displayName: "Create Deferred Entries" },
  { code: P.FINANCE_DEFERRED_UPDATE,      module: "finance",   resource: "deferred",       action: "update",    displayName: "Edit Deferred Entries" },
  { code: P.FINANCE_PERIOD_READ,          module: "finance",   resource: "period",         action: "read",      displayName: "View Fiscal Periods" },
  { code: P.FINANCE_PERIOD_MANAGE,        module: "finance",   resource: "period",         action: "manage",    displayName: "Manage Fiscal Periods" },
  { code: P.FINANCE_LOCK_DATE_MANAGE,     module: "finance",   resource: "lockDate",       action: "manage",    displayName: "Manage Lock Date" },
  { code: P.FINANCE_FISCAL_POSITION_READ,   module: "finance", resource: "fiscalPosition", action: "read",      displayName: "View Fiscal Positions" },
  { code: P.FINANCE_FISCAL_POSITION_CREATE, module: "finance", resource: "fiscalPosition", action: "create",    displayName: "Create Fiscal Positions" },
  { code: P.FINANCE_FISCAL_POSITION_UPDATE, module: "finance", resource: "fiscalPosition", action: "update",    displayName: "Edit Fiscal Positions" },
  { code: P.FINANCE_FISCAL_POSITION_DELETE, module: "finance", resource: "fiscalPosition", action: "delete",    displayName: "Delete Fiscal Positions" },
  { code: P.FINANCE_CURRENCY_READ,        module: "finance",   resource: "currency",       action: "read",      displayName: "View Currencies" },
  { code: P.FINANCE_CURRENCY_MANAGE,      module: "finance",   resource: "currency",       action: "manage",    displayName: "Manage Currencies" },
  { code: P.FINANCE_REPORT_READ,          module: "finance",   resource: "report",         action: "read",      displayName: "View Financial Reports" },
  { code: P.FINANCE_AUDIT_READ,           module: "finance",   resource: "auditTrail",     action: "read",      displayName: "View Audit Trail" },
  { code: P.FINANCE_SETTINGS_MANAGE,      module: "finance",   resource: "settings",       action: "manage",    displayName: "Manage Finance Settings" },
  // Contracting
  { code: P.CONTRACTING_HOTEL_READ,       module: "contracting", resource: "hotel",        action: "read",      displayName: "View Hotels" },
  { code: P.CONTRACTING_HOTEL_CREATE,     module: "contracting", resource: "hotel",        action: "create",    displayName: "Create Hotels" },
  { code: P.CONTRACTING_HOTEL_UPDATE,     module: "contracting", resource: "hotel",        action: "update",    displayName: "Edit Hotels" },
  { code: P.CONTRACTING_HOTEL_DELETE,     module: "contracting", resource: "hotel",        action: "delete",    displayName: "Delete Hotels" },
  { code: P.CONTRACTING_DESTINATION_READ,   module: "contracting", resource: "destination",action: "read",      displayName: "View Destinations" },
  { code: P.CONTRACTING_DESTINATION_CREATE, module: "contracting", resource: "destination",action: "create",    displayName: "Create Destinations" },
  { code: P.CONTRACTING_DESTINATION_UPDATE, module: "contracting", resource: "destination",action: "update",    displayName: "Edit Destinations" },
  { code: P.CONTRACTING_DESTINATION_DELETE, module: "contracting", resource: "destination",action: "delete",    displayName: "Delete Destinations" },
  { code: P.CONTRACTING_MARKET_READ,      module: "contracting", resource: "market",       action: "read",      displayName: "View Markets" },
  { code: P.CONTRACTING_MARKET_CREATE,    module: "contracting", resource: "market",       action: "create",    displayName: "Create Markets" },
  { code: P.CONTRACTING_MARKET_UPDATE,    module: "contracting", resource: "market",       action: "update",    displayName: "Edit Markets" },
  { code: P.CONTRACTING_MARKET_DELETE,    module: "contracting", resource: "market",       action: "delete",    displayName: "Delete Markets" },
  { code: P.CONTRACTING_ROOM_TYPE_READ,   module: "contracting", resource: "roomType",     action: "read",      displayName: "View Room Types" },
  { code: P.CONTRACTING_ROOM_TYPE_CREATE, module: "contracting", resource: "roomType",     action: "create",    displayName: "Create Room Types" },
  { code: P.CONTRACTING_ROOM_TYPE_UPDATE, module: "contracting", resource: "roomType",     action: "update",    displayName: "Edit Room Types" },
  { code: P.CONTRACTING_ROOM_TYPE_DELETE, module: "contracting", resource: "roomType",     action: "delete",    displayName: "Delete Room Types" },
  { code: P.CONTRACTING_MEAL_BASIS_READ,  module: "contracting", resource: "mealBasis",    action: "read",      displayName: "View Meal Bases" },
  { code: P.CONTRACTING_MEAL_BASIS_CREATE,module: "contracting", resource: "mealBasis",    action: "create",    displayName: "Create Meal Bases" },
  { code: P.CONTRACTING_MEAL_BASIS_UPDATE,module: "contracting", resource: "mealBasis",    action: "update",    displayName: "Edit Meal Bases" },
  { code: P.CONTRACTING_MEAL_BASIS_DELETE,module: "contracting", resource: "mealBasis",    action: "delete",    displayName: "Delete Meal Bases" },
  { code: P.CONTRACTING_CONTRACT_READ,    module: "contracting", resource: "contract",     action: "read",      displayName: "View Contracts" },
  { code: P.CONTRACTING_CONTRACT_CREATE,  module: "contracting", resource: "contract",     action: "create",    displayName: "Create Contracts" },
  { code: P.CONTRACTING_CONTRACT_UPDATE,  module: "contracting", resource: "contract",     action: "update",    displayName: "Edit Contracts" },
  { code: P.CONTRACTING_CONTRACT_DELETE,  module: "contracting", resource: "contract",     action: "delete",    displayName: "Delete Contracts" },
  { code: P.CONTRACTING_CONTRACT_POST,    module: "contracting", resource: "contract",     action: "post",      displayName: "Post Contracts" },
  { code: P.CONTRACTING_CONTRACT_PUBLISH, module: "contracting", resource: "contract",     action: "publish",   displayName: "Publish Contracts" },
  { code: P.CONTRACTING_RATE_READ,        module: "contracting", resource: "rate",         action: "read",      displayName: "View Rates" },
  { code: P.CONTRACTING_RATE_CREATE,      module: "contracting", resource: "rate",         action: "create",    displayName: "Create Rates" },
  { code: P.CONTRACTING_RATE_UPDATE,      module: "contracting", resource: "rate",         action: "update",    displayName: "Edit Rates" },
  { code: P.CONTRACTING_RATE_DELETE,      module: "contracting", resource: "rate",         action: "delete",    displayName: "Delete Rates" },
  { code: P.CONTRACTING_SEASON_READ,      module: "contracting", resource: "season",       action: "read",      displayName: "View Seasons" },
  { code: P.CONTRACTING_SEASON_CREATE,    module: "contracting", resource: "season",       action: "create",    displayName: "Create Seasons" },
  { code: P.CONTRACTING_SEASON_UPDATE,    module: "contracting", resource: "season",       action: "update",    displayName: "Edit Seasons" },
  { code: P.CONTRACTING_SEASON_DELETE,    module: "contracting", resource: "season",       action: "delete",    displayName: "Delete Seasons" },
  { code: P.CONTRACTING_SUPPLEMENT_READ,  module: "contracting", resource: "supplement",   action: "read",      displayName: "View Supplements" },
  { code: P.CONTRACTING_SUPPLEMENT_CREATE,module: "contracting", resource: "supplement",   action: "create",    displayName: "Create Supplements" },
  { code: P.CONTRACTING_SUPPLEMENT_UPDATE,module: "contracting", resource: "supplement",   action: "update",    displayName: "Edit Supplements" },
  { code: P.CONTRACTING_SUPPLEMENT_DELETE,module: "contracting", resource: "supplement",   action: "delete",    displayName: "Delete Supplements" },
  { code: P.CONTRACTING_OFFER_READ,       module: "contracting", resource: "offer",        action: "read",      displayName: "View Special Offers" },
  { code: P.CONTRACTING_OFFER_CREATE,     module: "contracting", resource: "offer",        action: "create",    displayName: "Create Special Offers" },
  { code: P.CONTRACTING_OFFER_UPDATE,     module: "contracting", resource: "offer",        action: "update",    displayName: "Edit Special Offers" },
  { code: P.CONTRACTING_OFFER_DELETE,     module: "contracting", resource: "offer",        action: "delete",    displayName: "Delete Special Offers" },
  { code: P.CONTRACTING_POLICY_READ,      module: "contracting", resource: "policy",       action: "read",      displayName: "View Policies" },
  { code: P.CONTRACTING_POLICY_CREATE,    module: "contracting", resource: "policy",       action: "create",    displayName: "Create Policies" },
  { code: P.CONTRACTING_POLICY_UPDATE,    module: "contracting", resource: "policy",       action: "update",    displayName: "Edit Policies" },
  { code: P.CONTRACTING_POLICY_DELETE,    module: "contracting", resource: "policy",       action: "delete",    displayName: "Delete Policies" },
  { code: P.CONTRACTING_MARKUP_READ,      module: "contracting", resource: "markup",       action: "read",      displayName: "View Markup Rules" },
  { code: P.CONTRACTING_MARKUP_CREATE,    module: "contracting", resource: "markup",       action: "create",    displayName: "Create Markup Rules" },
  { code: P.CONTRACTING_MARKUP_UPDATE,    module: "contracting", resource: "markup",       action: "update",    displayName: "Edit Markup Rules" },
  { code: P.CONTRACTING_MARKUP_DELETE,    module: "contracting", resource: "markup",       action: "delete",    displayName: "Delete Markup Rules" },
  { code: P.CONTRACTING_ALLOTMENT_READ,   module: "contracting", resource: "allotment",    action: "read",      displayName: "View Allotments" },
  { code: P.CONTRACTING_ALLOTMENT_CREATE, module: "contracting", resource: "allotment",    action: "create",    displayName: "Create Allotments" },
  { code: P.CONTRACTING_ALLOTMENT_UPDATE, module: "contracting", resource: "allotment",    action: "update",    displayName: "Edit Allotments" },
  { code: P.CONTRACTING_TARIFF_READ,      module: "contracting", resource: "tariff",       action: "read",      displayName: "View Tariffs" },
  { code: P.CONTRACTING_TARIFF_EXPORT,    module: "contracting", resource: "tariff",       action: "export",    displayName: "Export Tariffs" },
  { code: P.CONTRACTING_REPORT_READ,      module: "contracting", resource: "report",       action: "read",      displayName: "View Contracting Reports" },
  // Reservations
  { code: P.RESERVATIONS_BOOKING_READ,    module: "reservations", resource: "booking",     action: "read",      displayName: "View Bookings" },
  { code: P.RESERVATIONS_BOOKING_CREATE,  module: "reservations", resource: "booking",     action: "create",    displayName: "Create Bookings" },
  { code: P.RESERVATIONS_BOOKING_UPDATE,  module: "reservations", resource: "booking",     action: "update",    displayName: "Edit Bookings" },
  { code: P.RESERVATIONS_BOOKING_DELETE,  module: "reservations", resource: "booking",     action: "delete",    displayName: "Delete Bookings" },
  { code: P.RESERVATIONS_BOOKING_CONFIRM, module: "reservations", resource: "booking",     action: "confirm",   displayName: "Confirm Bookings" },
  { code: P.RESERVATIONS_BOOKING_CANCEL,  module: "reservations", resource: "booking",     action: "cancel",    displayName: "Cancel Bookings" },
  { code: P.RESERVATIONS_BOOKING_EXPORT,  module: "reservations", resource: "booking",     action: "export",    displayName: "Export Bookings" },
  { code: P.RESERVATIONS_PAYMENT_READ,    module: "reservations", resource: "payment",     action: "read",      displayName: "View Booking Payments" },
  { code: P.RESERVATIONS_PAYMENT_CREATE,  module: "reservations", resource: "payment",     action: "create",    displayName: "Create Booking Payments" },
  { code: P.RESERVATIONS_PAYMENT_CONFIRM, module: "reservations", resource: "payment",     action: "confirm",   displayName: "Confirm Booking Payments" },
  { code: P.RESERVATIONS_PAYMENT_CANCEL,  module: "reservations", resource: "payment",     action: "cancel",    displayName: "Cancel Booking Payments" },
  { code: P.RESERVATIONS_GUEST_READ,      module: "reservations", resource: "guest",       action: "read",      displayName: "View Guests" },
  { code: P.RESERVATIONS_GUEST_CREATE,    module: "reservations", resource: "guest",       action: "create",    displayName: "Create Guests" },
  { code: P.RESERVATIONS_GUEST_UPDATE,    module: "reservations", resource: "guest",       action: "update",    displayName: "Edit Guests" },
  { code: P.RESERVATIONS_GUEST_DELETE,    module: "reservations", resource: "guest",       action: "delete",    displayName: "Delete Guests" },
  { code: P.RESERVATIONS_VOUCHER_READ,    module: "reservations", resource: "voucher",     action: "read",      displayName: "View Vouchers" },
  { code: P.RESERVATIONS_VOUCHER_CREATE,  module: "reservations", resource: "voucher",     action: "create",    displayName: "Create Vouchers" },
  { code: P.RESERVATIONS_VOUCHER_EXPORT,  module: "reservations", resource: "voucher",     action: "export",    displayName: "Export Vouchers" },
  { code: P.RESERVATIONS_COMMUNICATION_READ,  module: "reservations", resource: "communication", action: "read",   displayName: "View Communications" },
  { code: P.RESERVATIONS_COMMUNICATION_CREATE, module: "reservations", resource: "communication", action: "create", displayName: "Send Communications" },
  { code: P.RESERVATIONS_HOTEL_CREDIT_READ,   module: "reservations", resource: "hotelCredit",   action: "read",   displayName: "View Hotel Credits" },
  { code: P.RESERVATIONS_HOTEL_CREDIT_CREATE, module: "reservations", resource: "hotelCredit",   action: "create", displayName: "Create Hotel Credits" },
  { code: P.RESERVATIONS_HOTEL_CREDIT_UPDATE, module: "reservations", resource: "hotelCredit",   action: "update", displayName: "Edit Hotel Credits" },
  { code: P.RESERVATIONS_REPORT_READ,     module: "reservations", resource: "report",      action: "read",      displayName: "View Reservation Reports" },
  // Traffic
  { code: P.TRAFFIC_JOB_READ,             module: "traffic",   resource: "job",            action: "read",      displayName: "View Traffic Jobs" },
  { code: P.TRAFFIC_JOB_CREATE,           module: "traffic",   resource: "job",            action: "create",    displayName: "Create Traffic Jobs" },
  { code: P.TRAFFIC_JOB_UPDATE,           module: "traffic",   resource: "job",            action: "update",    displayName: "Edit Traffic Jobs" },
  { code: P.TRAFFIC_JOB_DELETE,           module: "traffic",   resource: "job",            action: "delete",    displayName: "Delete Traffic Jobs" },
  { code: P.TRAFFIC_VEHICLE_READ,         module: "traffic",   resource: "vehicle",        action: "read",      displayName: "View Vehicles" },
  { code: P.TRAFFIC_VEHICLE_CREATE,       module: "traffic",   resource: "vehicle",        action: "create",    displayName: "Create Vehicles" },
  { code: P.TRAFFIC_VEHICLE_UPDATE,       module: "traffic",   resource: "vehicle",        action: "update",    displayName: "Edit Vehicles" },
  { code: P.TRAFFIC_VEHICLE_DELETE,       module: "traffic",   resource: "vehicle",        action: "delete",    displayName: "Delete Vehicles" },
  { code: P.TRAFFIC_DRIVER_READ,          module: "traffic",   resource: "driver",         action: "read",      displayName: "View Drivers" },
  { code: P.TRAFFIC_DRIVER_CREATE,        module: "traffic",   resource: "driver",         action: "create",    displayName: "Create Drivers" },
  { code: P.TRAFFIC_DRIVER_UPDATE,        module: "traffic",   resource: "driver",         action: "update",    displayName: "Edit Drivers" },
  { code: P.TRAFFIC_DRIVER_DELETE,        module: "traffic",   resource: "driver",         action: "delete",    displayName: "Delete Drivers" },
  { code: P.TRAFFIC_ZONE_READ,            module: "traffic",   resource: "zone",           action: "read",      displayName: "View Zones" },
  { code: P.TRAFFIC_ZONE_CREATE,          module: "traffic",   resource: "zone",           action: "create",    displayName: "Create Zones" },
  { code: P.TRAFFIC_ZONE_UPDATE,          module: "traffic",   resource: "zone",           action: "update",    displayName: "Edit Zones" },
  { code: P.TRAFFIC_ZONE_DELETE,          module: "traffic",   resource: "zone",           action: "delete",    displayName: "Delete Zones" },
  { code: P.TRAFFIC_AIRPORT_READ,         module: "traffic",   resource: "airport",        action: "read",      displayName: "View Airports" },
  { code: P.TRAFFIC_AIRPORT_CREATE,       module: "traffic",   resource: "airport",        action: "create",    displayName: "Create Airports" },
  { code: P.TRAFFIC_AIRPORT_UPDATE,       module: "traffic",   resource: "airport",        action: "update",    displayName: "Edit Airports" },
  { code: P.TRAFFIC_PRICING_READ,         module: "traffic",   resource: "pricing",        action: "read",      displayName: "View Transfer Pricing" },
  { code: P.TRAFFIC_PRICING_CREATE,       module: "traffic",   resource: "pricing",        action: "create",    displayName: "Create Transfer Pricing" },
  { code: P.TRAFFIC_PRICING_UPDATE,       module: "traffic",   resource: "pricing",        action: "update",    displayName: "Edit Transfer Pricing" },
  { code: P.TRAFFIC_PRICING_DELETE,       module: "traffic",   resource: "pricing",        action: "delete",    displayName: "Delete Transfer Pricing" },
  { code: P.TRAFFIC_DISPATCH_READ,        module: "traffic",   resource: "dispatch",       action: "read",      displayName: "View Dispatch Board" },
  { code: P.TRAFFIC_DISPATCH_MANAGE,      module: "traffic",   resource: "dispatch",       action: "manage",    displayName: "Manage Dispatch" },
  { code: P.TRAFFIC_ASSIGNMENT_READ,      module: "traffic",   resource: "assignment",     action: "read",      displayName: "View Job Assignments" },
  { code: P.TRAFFIC_ASSIGNMENT_MANAGE,    module: "traffic",   resource: "assignment",     action: "manage",    displayName: "Manage Job Assignments" },
  { code: P.TRAFFIC_GUEST_BOOKING_READ,   module: "traffic",   resource: "guestBooking",   action: "read",      displayName: "View Guest Bookings" },
  { code: P.TRAFFIC_GUEST_BOOKING_CREATE, module: "traffic",   resource: "guestBooking",   action: "create",    displayName: "Create Guest Bookings" },
  { code: P.TRAFFIC_GUEST_BOOKING_UPDATE, module: "traffic",   resource: "guestBooking",   action: "update",    displayName: "Edit Guest Bookings" },
  { code: P.TRAFFIC_REPORT_READ,          module: "traffic",   resource: "report",         action: "read",      displayName: "View Traffic Reports" },
  { code: P.TRAFFIC_SETTINGS_MANAGE,      module: "traffic",   resource: "settings",       action: "manage",    displayName: "Manage Traffic Settings" },
  // CRM
  { code: P.CRM_LEAD_READ,               module: "crm",       resource: "lead",           action: "read",      displayName: "View Leads" },
  { code: P.CRM_LEAD_CREATE,             module: "crm",       resource: "lead",           action: "create",    displayName: "Create Leads" },
  { code: P.CRM_LEAD_UPDATE,             module: "crm",       resource: "lead",           action: "update",    displayName: "Edit Leads" },
  { code: P.CRM_LEAD_DELETE,             module: "crm",       resource: "lead",           action: "delete",    displayName: "Delete Leads" },
  { code: P.CRM_OPPORTUNITY_READ,        module: "crm",       resource: "opportunity",    action: "read",      displayName: "View Opportunities" },
  { code: P.CRM_OPPORTUNITY_CREATE,      module: "crm",       resource: "opportunity",    action: "create",    displayName: "Create Opportunities" },
  { code: P.CRM_OPPORTUNITY_UPDATE,      module: "crm",       resource: "opportunity",    action: "update",    displayName: "Edit Opportunities" },
  { code: P.CRM_OPPORTUNITY_DELETE,      module: "crm",       resource: "opportunity",    action: "delete",    displayName: "Delete Opportunities" },
  { code: P.CRM_CUSTOMER_READ,           module: "crm",       resource: "customer",       action: "read",      displayName: "View Customers" },
  { code: P.CRM_CUSTOMER_CREATE,         module: "crm",       resource: "customer",       action: "create",    displayName: "Create Customers" },
  { code: P.CRM_CUSTOMER_UPDATE,         module: "crm",       resource: "customer",       action: "update",    displayName: "Edit Customers" },
  { code: P.CRM_CUSTOMER_DELETE,         module: "crm",       resource: "customer",       action: "delete",    displayName: "Delete Customers" },
  { code: P.CRM_EXCURSION_READ,          module: "crm",       resource: "excursion",      action: "read",      displayName: "View Excursions" },
  { code: P.CRM_EXCURSION_CREATE,        module: "crm",       resource: "excursion",      action: "create",    displayName: "Create Excursions" },
  { code: P.CRM_EXCURSION_UPDATE,        module: "crm",       resource: "excursion",      action: "update",    displayName: "Edit Excursions" },
  { code: P.CRM_EXCURSION_DELETE,        module: "crm",       resource: "excursion",      action: "delete",    displayName: "Delete Excursions" },
  { code: P.CRM_EXCURSION_EXPORT,        module: "crm",       resource: "excursion",      action: "export",    displayName: "Export Excursions" },
  { code: P.CRM_BOOKING_READ,            module: "crm",       resource: "booking",        action: "read",      displayName: "View CRM Bookings" },
  { code: P.CRM_BOOKING_CREATE,          module: "crm",       resource: "booking",        action: "create",    displayName: "Create CRM Bookings" },
  { code: P.CRM_BOOKING_UPDATE,          module: "crm",       resource: "booking",        action: "update",    displayName: "Edit CRM Bookings" },
  { code: P.CRM_BOOKING_DELETE,          module: "crm",       resource: "booking",        action: "delete",    displayName: "Delete CRM Bookings" },
  { code: P.CRM_BOOKING_CONFIRM,         module: "crm",       resource: "booking",        action: "confirm",   displayName: "Confirm CRM Bookings" },
  { code: P.CRM_BOOKING_CANCEL,          module: "crm",       resource: "booking",        action: "cancel",    displayName: "Cancel CRM Bookings" },
  { code: P.CRM_BOOKING_EXPORT,          module: "crm",       resource: "booking",        action: "export",    displayName: "Export CRM Bookings" },
  { code: P.CRM_SUPPLIER_READ,           module: "crm",       resource: "supplier",       action: "read",      displayName: "View Suppliers" },
  { code: P.CRM_SUPPLIER_CREATE,         module: "crm",       resource: "supplier",       action: "create",    displayName: "Create Suppliers" },
  { code: P.CRM_SUPPLIER_UPDATE,         module: "crm",       resource: "supplier",       action: "update",    displayName: "Edit Suppliers" },
  { code: P.CRM_ACTIVITY_READ,           module: "crm",       resource: "activity",       action: "read",      displayName: "View Activities" },
  { code: P.CRM_ACTIVITY_CREATE,         module: "crm",       resource: "activity",       action: "create",    displayName: "Create Activities" },
  { code: P.CRM_ACTIVITY_UPDATE,         module: "crm",       resource: "activity",       action: "update",    displayName: "Edit Activities" },
  { code: P.CRM_ACTIVITY_DELETE,         module: "crm",       resource: "activity",       action: "delete",    displayName: "Delete Activities" },
  { code: P.CRM_COST_SHEET_READ,         module: "crm",       resource: "costSheet",      action: "read",      displayName: "View Cost Sheets" },
  { code: P.CRM_COST_SHEET_CREATE,       module: "crm",       resource: "costSheet",      action: "create",    displayName: "Create Cost Sheets" },
  { code: P.CRM_COST_SHEET_UPDATE,       module: "crm",       resource: "costSheet",      action: "update",    displayName: "Edit Cost Sheets" },
  { code: P.CRM_COST_SHEET_DELETE,       module: "crm",       resource: "costSheet",      action: "delete",    displayName: "Delete Cost Sheets" },
  { code: P.CRM_REPORT_READ,             module: "crm",       resource: "report",         action: "read",      displayName: "View CRM Reports" },
  // Tour Operations
  { code: P.TOUR_OPS_FILE_READ,          module: "tour-ops",  resource: "file",           action: "read",      displayName: "View Ops Files" },
  { code: P.TOUR_OPS_FILE_CREATE,        module: "tour-ops",  resource: "file",           action: "create",    displayName: "Create Ops Files" },
  { code: P.TOUR_OPS_FILE_UPDATE,        module: "tour-ops",  resource: "file",           action: "update",    displayName: "Edit Ops Files" },
  { code: P.TOUR_OPS_FILE_DELETE,        module: "tour-ops",  resource: "file",           action: "delete",    displayName: "Delete Ops Files" },
  { code: P.TOUR_OPS_PACKAGE_READ,       module: "tour-ops",  resource: "package",        action: "read",      displayName: "View Tour Packages" },
  { code: P.TOUR_OPS_PACKAGE_CREATE,     module: "tour-ops",  resource: "package",        action: "create",    displayName: "Create Tour Packages" },
  { code: P.TOUR_OPS_PACKAGE_UPDATE,     module: "tour-ops",  resource: "package",        action: "update",    displayName: "Edit Tour Packages" },
  { code: P.TOUR_OPS_PACKAGE_DELETE,     module: "tour-ops",  resource: "package",        action: "delete",    displayName: "Delete Tour Packages" },
  { code: P.TOUR_OPS_QUOTATION_READ,     module: "tour-ops",  resource: "quotation",      action: "read",      displayName: "View Quotations" },
  { code: P.TOUR_OPS_QUOTATION_CREATE,   module: "tour-ops",  resource: "quotation",      action: "create",    displayName: "Create Quotations" },
  { code: P.TOUR_OPS_QUOTATION_UPDATE,   module: "tour-ops",  resource: "quotation",      action: "update",    displayName: "Edit Quotations" },
  { code: P.TOUR_OPS_QUOTATION_DELETE,   module: "tour-ops",  resource: "quotation",      action: "delete",    displayName: "Delete Quotations" },
  { code: P.TOUR_OPS_QUOTATION_EXPORT,   module: "tour-ops",  resource: "quotation",      action: "export",    displayName: "Export Quotations" },
  { code: P.TOUR_OPS_TICKET_READ,        module: "tour-ops",  resource: "flightTicket",   action: "read",      displayName: "View Flight Tickets" },
  { code: P.TOUR_OPS_TICKET_CREATE,      module: "tour-ops",  resource: "flightTicket",   action: "create",    displayName: "Create Flight Tickets" },
  { code: P.TOUR_OPS_TICKET_UPDATE,      module: "tour-ops",  resource: "flightTicket",   action: "update",    displayName: "Edit Flight Tickets" },
  { code: P.TOUR_OPS_TICKET_DELETE,      module: "tour-ops",  resource: "flightTicket",   action: "delete",    displayName: "Delete Flight Tickets" },
  { code: P.TOUR_OPS_TICKET_POST,        module: "tour-ops",  resource: "flightTicket",   action: "post",      displayName: "Post Flight Tickets" },
  { code: P.TOUR_OPS_TICKET_CANCEL,      module: "tour-ops",  resource: "flightTicket",   action: "cancel",    displayName: "Cancel Flight Tickets" },
  { code: P.TOUR_OPS_COMPONENT_READ,     module: "tour-ops",  resource: "component",      action: "read",      displayName: "View Tour Components" },
  { code: P.TOUR_OPS_COMPONENT_CREATE,   module: "tour-ops",  resource: "component",      action: "create",    displayName: "Create Tour Components" },
  { code: P.TOUR_OPS_COMPONENT_UPDATE,   module: "tour-ops",  resource: "component",      action: "update",    displayName: "Edit Tour Components" },
  { code: P.TOUR_OPS_COMPONENT_DELETE,   module: "tour-ops",  resource: "component",      action: "delete",    displayName: "Delete Tour Components" },
  { code: P.TOUR_OPS_DISPATCH_READ,      module: "tour-ops",  resource: "dispatch",       action: "read",      displayName: "View Tour Dispatch" },
  { code: P.TOUR_OPS_DISPATCH_MANAGE,    module: "tour-ops",  resource: "dispatch",       action: "manage",    displayName: "Manage Tour Dispatch" },
  { code: P.TOUR_OPS_PNL_READ,           module: "tour-ops",  resource: "pnl",            action: "read",      displayName: "View P&L Reports" },
  { code: P.TOUR_OPS_REPORT_READ,        module: "tour-ops",  resource: "report",         action: "read",      displayName: "View Tour Ops Reports" },
  // B2C
  { code: P.B2C_BRANDING_READ,           module: "b2c-site",  resource: "branding",       action: "read",      displayName: "View B2C Branding" },
  { code: P.B2C_BRANDING_MANAGE,         module: "b2c-site",  resource: "branding",       action: "manage",    displayName: "Manage B2C Branding" },
  { code: P.B2C_HERO_READ,               module: "b2c-site",  resource: "heroSlide",      action: "read",      displayName: "View Hero Slides" },
  { code: P.B2C_HERO_CREATE,             module: "b2c-site",  resource: "heroSlide",      action: "create",    displayName: "Create Hero Slides" },
  { code: P.B2C_HERO_UPDATE,             module: "b2c-site",  resource: "heroSlide",      action: "update",    displayName: "Edit Hero Slides" },
  { code: P.B2C_HERO_DELETE,             module: "b2c-site",  resource: "heroSlide",      action: "delete",    displayName: "Delete Hero Slides" },
  { code: P.B2C_PAGE_READ,               module: "b2c-site",  resource: "page",           action: "read",      displayName: "View Pages" },
  { code: P.B2C_PAGE_CREATE,             module: "b2c-site",  resource: "page",           action: "create",    displayName: "Create Pages" },
  { code: P.B2C_PAGE_UPDATE,             module: "b2c-site",  resource: "page",           action: "update",    displayName: "Edit Pages" },
  { code: P.B2C_PAGE_DELETE,             module: "b2c-site",  resource: "page",           action: "delete",    displayName: "Delete Pages" },
  { code: P.B2C_BLOG_READ,               module: "b2c-site",  resource: "blog",           action: "read",      displayName: "View Blog Posts" },
  { code: P.B2C_BLOG_CREATE,             module: "b2c-site",  resource: "blog",           action: "create",    displayName: "Create Blog Posts" },
  { code: P.B2C_BLOG_UPDATE,             module: "b2c-site",  resource: "blog",           action: "update",    displayName: "Edit Blog Posts" },
  { code: P.B2C_BLOG_DELETE,             module: "b2c-site",  resource: "blog",           action: "delete",    displayName: "Delete Blog Posts" },
  { code: P.B2C_FAQ_READ,                module: "b2c-site",  resource: "faq",            action: "read",      displayName: "View FAQs" },
  { code: P.B2C_FAQ_CREATE,              module: "b2c-site",  resource: "faq",            action: "create",    displayName: "Create FAQs" },
  { code: P.B2C_FAQ_UPDATE,              module: "b2c-site",  resource: "faq",            action: "update",    displayName: "Edit FAQs" },
  { code: P.B2C_FAQ_DELETE,              module: "b2c-site",  resource: "faq",            action: "delete",    displayName: "Delete FAQs" },
  { code: P.B2C_TESTIMONIAL_READ,        module: "b2c-site",  resource: "testimonial",    action: "read",      displayName: "View Testimonials" },
  { code: P.B2C_TESTIMONIAL_CREATE,      module: "b2c-site",  resource: "testimonial",    action: "create",    displayName: "Create Testimonials" },
  { code: P.B2C_TESTIMONIAL_UPDATE,      module: "b2c-site",  resource: "testimonial",    action: "update",    displayName: "Edit Testimonials" },
  { code: P.B2C_TESTIMONIAL_DELETE,      module: "b2c-site",  resource: "testimonial",    action: "delete",    displayName: "Delete Testimonials" },
  { code: P.B2C_INQUIRY_READ,            module: "b2c-site",  resource: "inquiry",        action: "read",      displayName: "View Inquiries" },
  { code: P.B2C_INQUIRY_DELETE,          module: "b2c-site",  resource: "inquiry",        action: "delete",    displayName: "Delete Inquiries" },
  { code: P.B2C_NEWSLETTER_READ,         module: "b2c-site",  resource: "newsletter",     action: "read",      displayName: "View Newsletter Subscribers" },
  { code: P.B2C_NEWSLETTER_MANAGE,       module: "b2c-site",  resource: "newsletter",     action: "manage",    displayName: "Manage Newsletter" },
  { code: P.B2C_MARKUP_READ,             module: "b2c-site",  resource: "markup",         action: "read",      displayName: "View B2C Markup Rules" },
  { code: P.B2C_MARKUP_CREATE,           module: "b2c-site",  resource: "markup",         action: "create",    displayName: "Create B2C Markup Rules" },
  { code: P.B2C_MARKUP_UPDATE,           module: "b2c-site",  resource: "markup",         action: "update",    displayName: "Edit B2C Markup Rules" },
  { code: P.B2C_MARKUP_DELETE,           module: "b2c-site",  resource: "markup",         action: "delete",    displayName: "Delete B2C Markup Rules" },
  // B2B
  { code: P.B2B_TOUR_OPERATOR_READ,      module: "b2b-portal", resource: "tourOperator",  action: "read",      displayName: "View Tour Operators" },
  { code: P.B2B_TOUR_OPERATOR_CREATE,    module: "b2b-portal", resource: "tourOperator",  action: "create",    displayName: "Create Tour Operators" },
  { code: P.B2B_TOUR_OPERATOR_UPDATE,    module: "b2b-portal", resource: "tourOperator",  action: "update",    displayName: "Edit Tour Operators" },
  { code: P.B2B_TOUR_OPERATOR_DELETE,    module: "b2b-portal", resource: "tourOperator",  action: "delete",    displayName: "Delete Tour Operators" },
  { code: P.B2B_TRAVEL_AGENT_READ,       module: "b2b-portal", resource: "travelAgent",   action: "read",      displayName: "View Travel Agents" },
  { code: P.B2B_TRAVEL_AGENT_CREATE,     module: "b2b-portal", resource: "travelAgent",   action: "create",    displayName: "Create Travel Agents" },
  { code: P.B2B_TRAVEL_AGENT_UPDATE,     module: "b2b-portal", resource: "travelAgent",   action: "update",    displayName: "Edit Travel Agents" },
  { code: P.B2B_TRAVEL_AGENT_DELETE,     module: "b2b-portal", resource: "travelAgent",   action: "delete",    displayName: "Delete Travel Agents" },
  { code: P.B2B_PARTNER_USER_READ,       module: "b2b-portal", resource: "partnerUser",   action: "read",      displayName: "View Partner Users" },
  { code: P.B2B_PARTNER_USER_CREATE,     module: "b2b-portal", resource: "partnerUser",   action: "create",    displayName: "Create Partner Users" },
  { code: P.B2B_PARTNER_USER_UPDATE,     module: "b2b-portal", resource: "partnerUser",   action: "update",    displayName: "Edit Partner Users" },
  { code: P.B2B_RESERVATION_READ,        module: "b2b-portal", resource: "reservation",   action: "read",      displayName: "View B2B Reservations" },
  { code: P.B2B_RESERVATION_CREATE,      module: "b2b-portal", resource: "reservation",   action: "create",    displayName: "Create B2B Reservations" },
  { code: P.B2B_RESERVATION_UPDATE,      module: "b2b-portal", resource: "reservation",   action: "update",    displayName: "Edit B2B Reservations" },
  { code: P.B2B_VOUCHER_READ,            module: "b2b-portal", resource: "voucher",       action: "read",      displayName: "View B2B Vouchers" },
  { code: P.B2B_VOUCHER_CREATE,          module: "b2b-portal", resource: "voucher",       action: "create",    displayName: "Create B2B Vouchers" },
  { code: P.B2B_CREDIT_READ,             module: "b2b-portal", resource: "credit",        action: "read",      displayName: "View Partner Credits" },
  { code: P.B2B_CREDIT_MANAGE,           module: "b2b-portal", resource: "credit",        action: "manage",    displayName: "Manage Partner Credits" },
  { code: P.B2B_MARKUP_READ,             module: "b2b-portal", resource: "markup",        action: "read",      displayName: "View B2B Markup Rules" },
  { code: P.B2B_MARKUP_CREATE,           module: "b2b-portal", resource: "markup",        action: "create",    displayName: "Create B2B Markup Rules" },
  { code: P.B2B_MARKUP_UPDATE,           module: "b2b-portal", resource: "markup",        action: "update",    displayName: "Edit B2B Markup Rules" },
  { code: P.B2B_MARKUP_DELETE,           module: "b2b-portal", resource: "markup",        action: "delete",    displayName: "Delete B2B Markup Rules" },
  { code: P.B2B_RATE_SHEET_READ,         module: "b2b-portal", resource: "rateSheet",     action: "read",      displayName: "View Rate Sheets" },
  { code: P.B2B_RATE_SHEET_CREATE,       module: "b2b-portal", resource: "rateSheet",     action: "create",    displayName: "Create Rate Sheets" },
  { code: P.B2B_RATE_SHEET_UPDATE,       module: "b2b-portal", resource: "rateSheet",     action: "update",    displayName: "Edit Rate Sheets" },
  { code: P.B2B_RATE_SHEET_DELETE,       module: "b2b-portal", resource: "rateSheet",     action: "delete",    displayName: "Delete Rate Sheets" },
  { code: P.B2B_REPORT_READ,             module: "b2b-portal", resource: "report",        action: "read",      displayName: "View B2B Reports" },

  // ── Nile Cruises ──────────────────────────────────────────────────────────
  { code: P.NC_DASHBOARD_READ,           module: "nile-cruises", resource: "dashboard",   action: "read",      displayName: "View Cruise Dashboard" },
  { code: P.NC_BOAT_READ,                module: "nile-cruises", resource: "boat",        action: "read",      displayName: "View Cruise Boats" },
  { code: P.NC_BOAT_CREATE,              module: "nile-cruises", resource: "boat",        action: "create",    displayName: "Create Cruise Boats" },
  { code: P.NC_BOAT_UPDATE,              module: "nile-cruises", resource: "boat",        action: "update",    displayName: "Edit Cruise Boats" },
  { code: P.NC_BOAT_DELETE,              module: "nile-cruises", resource: "boat",        action: "delete",    displayName: "Delete Cruise Boats" },
  { code: P.NC_CONTRACT_READ,            module: "nile-cruises", resource: "contract",    action: "read",      displayName: "View Cruise Contracts" },
  { code: P.NC_CONTRACT_CREATE,          module: "nile-cruises", resource: "contract",    action: "create",    displayName: "Create Cruise Contracts" },
  { code: P.NC_CONTRACT_UPDATE,          module: "nile-cruises", resource: "contract",    action: "update",    displayName: "Edit Cruise Contracts" },
  { code: P.NC_CONTRACT_DELETE,          module: "nile-cruises", resource: "contract",    action: "delete",    displayName: "Delete Cruise Contracts" },
  { code: P.NC_CONTRACT_PUBLISH,         module: "nile-cruises", resource: "contract",    action: "publish",   displayName: "Publish Cruise Contracts" },
  { code: P.NC_DEPARTURE_READ,           module: "nile-cruises", resource: "departure",   action: "read",      displayName: "View Cruise Departures" },
  { code: P.NC_DEPARTURE_CREATE,         module: "nile-cruises", resource: "departure",   action: "create",    displayName: "Create Cruise Departures" },
  { code: P.NC_DEPARTURE_UPDATE,         module: "nile-cruises", resource: "departure",   action: "update",    displayName: "Edit Cruise Departures" },
  { code: P.NC_DEPARTURE_DELETE,         module: "nile-cruises", resource: "departure",   action: "delete",    displayName: "Delete Cruise Departures" },
  { code: P.NC_BOOKING_READ,             module: "nile-cruises", resource: "booking",     action: "read",      displayName: "View Cruise Bookings" },
  { code: P.NC_BOOKING_CREATE,           module: "nile-cruises", resource: "booking",     action: "create",    displayName: "Create Cruise Bookings" },
  { code: P.NC_BOOKING_UPDATE,           module: "nile-cruises", resource: "booking",     action: "update",    displayName: "Edit Cruise Bookings" },
  { code: P.NC_BOOKING_DELETE,           module: "nile-cruises", resource: "booking",     action: "delete",    displayName: "Delete Cruise Bookings" },
  { code: P.NC_BOOKING_CONFIRM,          module: "nile-cruises", resource: "booking",     action: "confirm",   displayName: "Confirm Cruise Bookings" },
  { code: P.NC_BOOKING_CANCEL,           module: "nile-cruises", resource: "booking",     action: "cancel",    displayName: "Cancel Cruise Bookings" },
  { code: P.NC_MANIFEST_READ,            module: "nile-cruises", resource: "manifest",    action: "read",      displayName: "View Cruise Manifests" },
  { code: P.NC_MANIFEST_GENERATE,        module: "nile-cruises", resource: "manifest",    action: "generate",  displayName: "Generate Cruise Manifests" },
  { code: P.NC_MANIFEST_SUBMIT,          module: "nile-cruises", resource: "manifest",    action: "submit",    displayName: "Submit Cruise Manifests" },
  { code: P.NC_REPORTS_READ,             module: "nile-cruises", resource: "reports",     action: "read",      displayName: "View Cruise Reports" },
  { code: P.NC_SEARCH_READ,              module: "nile-cruises", resource: "search",      action: "read",      displayName: "Search Cruise Availability" },
  { code: P.NC_SETTINGS_READ,            module: "nile-cruises", resource: "settings",    action: "read",      displayName: "View Cruise Settings" },
  { code: P.NC_SETTINGS_UPDATE,          module: "nile-cruises", resource: "settings",    action: "update",    displayName: "Edit Cruise Settings" },
];
