/**
 * Captures the screenshots the partner manual refers to.
 *
 * Run it rather than re-shooting by hand: a manual whose pictures no longer
 * match the product is worse than one with none, and hand-taken screenshots
 * rot within a month of the first UI change.
 *
 *   pnpm dev                                  # in another terminal
 *   npx tsx --env-file=.env scripts/capture-help-screenshots.ts
 *
 * It creates a throwaway partner login against existing data, signs in through
 * the real login form, captures each page, then deletes the account again.
 * Nothing here touches a real partner's login or appears in their audit trail
 * beyond the temporary account's own rows, which are removed at the end.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import bcrypt from "bcryptjs";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";
import { Secret, TOTP } from "otpauth";
import { chromium } from "@playwright/test";

import { generateBackupCodes, hashBackupCode } from "../src/lib/totp";

const BASE = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
const OUT = path.join(process.cwd(), "public", "help", "b2b");
const EMAIL = "help-capture@local.invalid";
const PASSWORD = "CaptureOnly123!";

/** Each shot the manual asks for, by the filename its section names. */
const SHOTS: { file: string; path: string; wait?: string }[] = [
  { file: "02-dashboard.png", path: "/b2b" },
  { file: "03-search.png", path: "/b2b/search" },
  { file: "05-booking.png", path: "/b2b/bookings" },
  { file: "06-booking-detail.png", path: "/b2b/bookings" },
  { file: "07-credit.png", path: "/b2b/credit" },
  { file: "09-documents.png", path: "/b2b/rate-sheets" },
];

const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) });

async function main() {
  await mkdir(OUT, { recursive: true });

  const operator = await db.tourOperator.findFirst({
    where: { active: true },
    select: { id: true, companyId: true, name: true, portalEnabled: true },
  });
  if (!operator) throw new Error("No tour operator to capture against — seed one first.");

  const restoreportal = operator.portalEnabled;
  await db.tourOperator.update({ where: { id: operator.id }, data: { portalEnabled: true } });

  const secret = new Secret({ size: 20 }).base32;
  await db.user.deleteMany({ where: { email: EMAIL } });
  const user = await db.user.create({
    data: {
      email: EMAIL,
      name: "Guide Capture",
      password: await bcrypt.hash(PASSWORD, 10),
      companyId: operator.companyId,
      tourOperatorId: operator.id,
      partnerRole: "PARTNER_ADMIN",
      twoFactorEnabled: true,
      twoFactorSecret: secret,
      twoFactorBackupCodes: generateBackupCodes().map(hashBackupCode),
    },
  });

  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });

  try {
    // The login screen is itself a figure in section 1.
    await page.goto(`${BASE}/b2b/login`, { waitUntil: "networkidle" });
    await page.screenshot({ path: path.join(OUT, "01-login.png") });

    await page.fill('input[type="email"]', EMAIL);
    await page.fill('input[type="password"]', PASSWORD);
    await page.click('button[type="submit"]');
    await page.waitForSelector("#otp", { timeout: 15_000 });

    const totp = new TOTP({
      issuer: "iTourTMS",
      label: EMAIL,
      algorithm: "SHA1",
      digits: 6,
      period: 30,
      secret: Secret.fromBase32(secret),
    });
    await page.fill("#otp", totp.generate());
    await page.waitForURL(`${BASE}/b2b`, { timeout: 20_000 });

    for (const shot of SHOTS) {
      await page.goto(`${BASE}${shot.path}`, { waitUntil: "networkidle" });
      // Give a client-rendered list a moment to replace its skeletons.
      await page.waitForTimeout(1200);
      await page.screenshot({ path: path.join(OUT, shot.file) });
      console.log("captured", shot.file);
    }

    // Sections whose figure is a screen we cannot reach without live data get
    // a note instead of a stale or empty picture.
    await writeFile(
      path.join(OUT, "README.md"),
      [
        "# Partner manual screenshots",
        "",
        "Generated by `scripts/capture-help-screenshots.ts`. Do not edit by hand —",
        "re-run the script after any change to the portal UI.",
        "",
        "`04-price.png` and `08-markup.png` are not captured automatically: they",
        "need a search result and a markup rule that only exist with commercial",
        "seed data. Capture them by hand when that data is in place.",
        "",
      ].join("\n"),
    );
  } finally {
    await browser.close();
    await db.partnerAuditEvent.deleteMany({ where: { userId: user.id } });
    await db.user.delete({ where: { id: user.id } });
    await db.tourOperator.update({
      where: { id: operator.id },
      data: { portalEnabled: restoreportal },
    });
    await db.$disconnect();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
